name = "webhook"
main = "./workers/dist/index.js"
account_id = "aa6a672906a96132f0ffdc582c69537a"
route = "webhook.kweeksnews.com/*"
compatibility_date = "2022-07-23"

[[kv_namespaces]]
binding = "CONFIG"
id = "1ea0b7b9a160445b905f6bbc23802013"

[build]
command = "npm run build && cd workers && npm run build"

[site]
bucket = "./dist"
