name = "webhook"
type = "javascript"
account_id = "aa6a672906a96132f0ffdc582c69537a"
zone_id = "f14939370d152d28d026295478d20daa"
route = "webhook.kweeksnews.com/*"
kv_namespaces = [
  { binding = "KV", id = "1ea0b7b9a160445b905f6bbc23802013", preview_id = "1ea0b7b9a160445b905f6bbc23802013" }
]

[build]
command = "npm ci && npm run build"
cwd = "./workers"

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
entry-point = "./workers"
